spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:tcp://localhost/~/mytrip
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create


file:
  dir: C:/Backend/WorkSpace_IntelliJ/mytrip/src/main/resources/static/upload/budget/


